includes:
  - configs/s2ef/2M/base-is2rv2e.yml

model:
  name: gemnet_is2rv2e
  num_spherical: 8
#  num_radial: 255 # 为了适应vector边的嵌入维度
  num_radial: 256
  num_radial_e: 128
  num_blocks: 6
  emb_size_atom: 128 # 256+128其中128为原子标签信息
  emb_size_atom_e: 256 # 256+128其中128为原子标签信息
  emb_size_edge: 512
#  emb_size_edge: 768 # 为了适应vector边的嵌入维度
  emb_size_trip_in: 64
  emb_size_trip_out: 64
  emb_size_quad_in: 32
  emb_size_quad_out: 32
  emb_size_aint_in: 64
  emb_size_aint_out: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  num_before_skip: 2
  num_after_skip: 2
  num_concat: 1
  num_atom: 3
  num_output_afteratom: 3
  cutoff: 8.0
  cutoff_qint: 8.0
  cutoff_aeaint: 8.0
  cutoff_aint: 8.0
  max_neighbors: 10
  max_neighbors_qint: 8
  max_neighbors_aeaint: 20
  max_neighbors_aint: 1000
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  sbf:
    name: legendre_outer
  extensive: True
  output_init: HeOrthogonal
  activation: silu
  scale_file: configs/s2ef/all/gemnet/scaling_factors/gemnet-oc-is2rv2e.pt

#  regress_forces: True
  regress_forces: False
#  direct_forces: True
  direct_forces: False
  forces_coupled: True
  update_v: True # 新增参数，是否预测坐标/向量
  edge_mask: True # 是否对边进行筛选
  edge_mask_tags: 0

  quad_interaction: False
  atom_edge_interaction: True
  edge_atom_interaction: True
  atom_interaction: True

  num_atom_emb_layers: 2
  num_global_out_layers: 2
  qint_tags: [0, 1]
#  qint_tags: [1, 2]

optim:
  batch_size: 6
  eval_batch_size: 6
  load_balancing: atoms
  eval_every: 2000
  num_workers: 2
  lr_initial: 5.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  scheduler: ReduceLROnPlateau
#  scheduler: CosineAnnealingLR
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 100
  force_coefficient: 100
  v_coefficient: 1
  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
  loss_energy: mae
  loss_force: l2mae
  loss_vector: mae_v
  weight_decay: 0
  #  weight_decay: 0.1
  #  T_max: 2000000 # for CosineAnnealingLR
  v_batch: 20000
