trainer: is2rse # trainer名字

dataset:
  - src: /tmp/vector/train
    normalize_labels: False # 标准化开关
#    target_mean: -1.3742
#    target_std: 2.0359
  - src: /tmp/vector/val
  - src: /tmp/vector/test


logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
#  labels:
#    - potential energy
  labels:
    positions potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
