trainer: energy

dataset:
  - src: /work/home/liunz/dataset/OC22/is2re/train/
    normalize_labels: True
    target_mean: -523.8716
    target_std: 228.1776
  - src: /work/home/liunz/dataset/OC22/is2re/val/
  - src: /work/home/liunz/dataset/OC22/is2re/test/

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
