trainer: is2rsv

dataset:
  train:
    src: /data2/liud/dataset/OC22/is2re/train
    normalize_labels: False
  val:
    src: /data2/liud/dataset/OC22/is2re/val

logger: tensorboard

task:
  dataset: oc22_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  primary_metric: average_distance_within_threshold
  labels:
    - relaxed energy
  train_on_free_atoms: False
  eval_on_free_atoms: False