trainer: energy_ddp

dataset:
  - src: /home/wuyinkai/liud/dataset/OC20/is2re10k/select_data/vector_copy/train
    normalize_labels: True # 预测能量时，对能量进行标准化
    target_mean: -1.5260
    target_std: 2.2793
#    grad_target_mean: 0.0
#    grad_target_std: 2.887317180633545
  - src: /home/wuyinkai/liud/dataset/OC20/is2re10k/select_data/vector_copy/val
  - src: /home/wuyinkai/liud/dataset/OC20/is2re10k/select_data/vector_copy/val


logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
