trainer: is2rfse # trainer名字

dataset:
  - src: /home/wuyinkai/liud/dataset/OC20/is2re10k/select_data/vector/train
    normalize_labels: False # 标准化开关
#    target_mean: -1.4191
#    target_std: 2.0206
#    grad_target_mean: 0.0
#    grad_target_std: 2.887317180633545
  - src: /home/wuyinkai/liud/dataset/OC20/is2re10k/select_data/vector/val
  - src: /home/wuyinkai/liud/dataset/OC20/is2re10k/select_data/vector/test


logger: tensorboard


task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
#  labels:
#    - potential energy
  labels:
    positions potential energy
  grad_input: atomic forces
  train_on_free_atoms: False
  eval_on_free_atoms: False
