trainer: forces

dataset:
  - src: /data2/liud/dataset/OC20/is2re100k/origin/train
#    normalize_labels: False # 预测能量时，对能量进行标准化
    normalize_labels: True # 预测能量时，对能量进行标准化
    target_mean: -1.5188
    target_std: 2.2821
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: /data2/liud/dataset/OC20/is2re100k/origin/val
  - src: /data2/liud/dataset/OC20/is2re100k/origin/test


logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
#  labels:
#    positions potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
