trainer: is2rve # trainer名字

dataset:
  - src: /home/wuyinkai/liud/dataset/OC20/is2re100k/select_data/tags/50k/vector/train
    normalize_labels: True # 标准化开关
    target_mean: -1.3761
    target_std: 2.0340
  - src: /home/wuyinkai/liud/dataset/OC20/is2re100k/select_data/tags/50k/vector/val
  - src: /home/wuyinkai/liud/dataset/OC20/is2re100k/select_data/tags/50k/vector/test


logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
#  labels:
#    - potential energy
  labels:
    positions potential energy
  grad_input: atomic forces
  train_on_free_atoms: False
  eval_on_free_atoms: False
